//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginside_FYAN_Bot_Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loginside_FYAN_Bot_Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loginside FYAN Bot Service.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_ContentPlaceHolder1_ctl00_btnSaveUser.
        /// </summary>
        internal static string id_btn_chg_pwd {
            get {
                return ResourceManager.GetString("id_btn_chg_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgcheckin.
        /// </summary>
        internal static string id_btn_chkin {
            get {
                return ResourceManager.GetString("id_btn_chkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgcheckout.
        /// </summary>
        internal static string id_btn_chkout {
            get {
                return ResourceManager.GetString("id_btn_chkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kt_login_signin_submit.
        /// </summary>
        internal static string id_btn_login {
            get {
                return ResourceManager.GetString("id_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_ContentPlaceHolder1_ctl00_txtPasswordConfix.
        /// </summary>
        internal static string id_cfm_pwd {
            get {
                return ResourceManager.GetString("id_cfm_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-3.
        /// </summary>
        internal static string id_inp_id {
            get {
                return ResourceManager.GetString("id_inp_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-5.
        /// </summary>
        internal static string id_inp_otp {
            get {
                return ResourceManager.GetString("id_inp_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-4.
        /// </summary>
        internal static string id_inp_pwd {
            get {
                return ResourceManager.GetString("id_inp_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id_Ins.
        /// </summary>
        internal static string id_ins {
            get {
                return ResourceManager.GetString("id_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_ContentPlaceHolder1_ctl00_txtPassword.
        /// </summary>
        internal static string id_new_pwd {
            get {
                return ResourceManager.GetString("id_new_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_ContentPlaceHolder1_ctl00_txtPasswordOld.
        /// </summary>
        internal static string id_old_pwd {
            get {
                return ResourceManager.GetString("id_old_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://inside.fptshop.com.vn/.
        /// </summary>
        internal static string link_ins {
            get {
                return ResourceManager.GetString("link_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Ins.
        /// </summary>
        internal static string pwd_ins {
            get {
                return ResourceManager.GetString("pwd_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Prev_1.
        /// </summary>
        internal static string pwd_prev_1 {
            get {
                return ResourceManager.GetString("pwd_prev_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Prev_2.
        /// </summary>
        internal static string pwd_prev_2 {
            get {
                return ResourceManager.GetString("pwd_prev_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Prev_3.
        /// </summary>
        internal static string pwd_prev_3 {
            get {
                return ResourceManager.GetString("pwd_prev_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec_Key.
        /// </summary>
        internal static string sec_key {
            get {
                return ResourceManager.GetString("sec_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmr_In.
        /// </summary>
        internal static string tmr_in {
            get {
                return ResourceManager.GetString("tmr_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmr_Out.
        /// </summary>
        internal static string tmr_out {
            get {
                return ResourceManager.GetString("tmr_out", resourceCulture);
            }
        }
    }
}
