//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginside_FYAN_Bot_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loginside_FYAN_Bot_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loginside FYAN Bot GUI.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loginside FYAN Bot.
        /// </summary>
        internal static string bot_name {
            get {
                return ResourceManager.GetString("bot_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day_Chg_Pwd.
        /// </summary>
        internal static string day_chg_pwd {
            get {
                return ResourceManager.GetString("day_chg_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id_Ins.
        /// </summary>
        internal static string id_ins {
            get {
                return ResourceManager.GetString("id_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pOff {
            get {
                object obj = ResourceManager.GetObject("pOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Ins.
        /// </summary>
        internal static string pwd_ins {
            get {
                return ResourceManager.GetString("pwd_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwd_Prev.
        /// </summary>
        internal static string pwd_prev {
            get {
                return ResourceManager.GetString("pwd_prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sBack {
            get {
                return ResourceManager.GetStream("sBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sChange {
            get {
                return ResourceManager.GetStream("sChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec_Key.
        /// </summary>
        internal static string sec_key {
            get {
                return ResourceManager.GetString("sec_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loginside FYAN Bot Service.
        /// </summary>
        internal static string serv_name {
            get {
                return ResourceManager.GetString("serv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sHover {
            get {
                return ResourceManager.GetStream("sHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sNext {
            get {
                return ResourceManager.GetStream("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream sPress {
            get {
                return ResourceManager.GetStream("sPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmr_In.
        /// </summary>
        internal static string tmr_in {
            get {
                return ResourceManager.GetString("tmr_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmr_Out.
        /// </summary>
        internal static string tmr_out {
            get {
                return ResourceManager.GetString("tmr_out", resourceCulture);
            }
        }
    }
}
