//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loginside_FYAN_Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loginside_FYAN_Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ci.
        /// </summary>
        internal static string id_btn_chkin {
            get {
                return ResourceManager.GetString("id_btn_chkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co.
        /// </summary>
        internal static string id_btn_chkout {
            get {
                return ResourceManager.GetString("id_btn_chkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kt_login_signin_submit.
        /// </summary>
        internal static string id_btn_login {
            get {
                return ResourceManager.GetString("id_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-3.
        /// </summary>
        internal static string id_inp_id {
            get {
                return ResourceManager.GetString("id_inp_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-4.
        /// </summary>
        internal static string id_inp_pwd {
            get {
                return ResourceManager.GetString("id_inp_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mat-input-5.
        /// </summary>
        internal static string id_inpt_otp {
            get {
                return ResourceManager.GetString("id_inpt_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://inside.fptshop.com.vn/.
        /// </summary>
        internal static string link_ins {
            get {
                return ResourceManager.GetString("link_ins", resourceCulture);
            }
        }
    }
}
